name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  Setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable
  build_hello:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Build and test in hello directory
      run: |
        cd hello
        cargo build --verbose
  build_variables:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Build and test in variables directory
      run: |
        cd variables
        cargo build --verbose
  run_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Run tests
      run: |
        cd hello
        cargo test
        cd ../variables
        cargo test
