name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    needs: [hello, variables, test]
    strategy:
      matrix:
        include:
          - name: hello
            job: build_hello
          - name: variables
            job: build_variables
          - name: test
            job: test

  no_dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: No dependencies step
        run: echo "This job has no dependencies"