on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_variables:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Build and test in variables directory
      run: |
        cd variables
        cargo build --verbose
        cargo test --verbose

  build_without_dependencies:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Build and test without dependencies
      run: |
        cd hello
        cargo build --verbose
        cargo test --verbose
